"""Adds notes column to links table

Revision ID: 1584c8eaaac6
Revises: 9d69ed3d4c1f
Create Date: 2020-06-06 19:42:45.934361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1584c8eaaac6"
down_revision = "9d69ed3d4c1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("notes", sa.Text(), nullable=True))
    op.create_index(op.f("ix_links_link"), "links", ["link"], unique=True)
    op.drop_constraint("links_link_key", "links", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("links_link_key", "links", ["link"])
    op.drop_index(op.f("ix_links_link"), table_name="links")
    op.drop_column("links", "notes")
    # ### end Alembic commands ###
