"""make url not unique

Revision ID: f8fb1f7af8f5
Revises: 1584c8eaaac6
Create Date: 2020-06-06 19:50:01.327892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8fb1f7af8f5"
down_revision = "1584c8eaaac6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("links_url_key", "links", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("links_url_key", "links", ["url"])
    # ### end Alembic commands ###
